### ISSUE TITLE
Client has already been disposed

### ISSUE THREAD

**Issue by Mansi1** [actions/upload-artifact#185]
With the provided path, there will be 6996 files uploaded
An error has been caught http-client index 1, retrying the upload
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Exponential backoff for retry #1. Waiting for 5699.0598393304535 milliseconds before continuing the upload at offset 0
An error has been caught http-client index 0, retrying the upload
Error: Client has already been disposed.
    at HttpClient.request (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:5691:19)
    at HttpClient.sendStream (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:5652:21)
    at UploadHttpClient.<anonymous> (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:7099:37)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:6829:71
    at new Promise (<anonymous>)
    at module.exports.608.__awaiter (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:6825:12)
    at uploadChunkRequest (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:7097:46)
    at UploadHttpClient.<anonymous> (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:7134:38)
    at Generator.next (<anonymous>)

**Comment by xerxesb** [comment]
Same issue here with my build. Trying to preserve artifacts across build steps and get the following error

> Total file count: 1826 ---- Processed file #435 (23.8%)
Total file count: 1826 ---- Processed file #435 (23.8%)
An error occurred while attempting to download a file
Error: Client has already been disposed.
    at HttpClient.request (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:5237:19)
    at HttpClient.get (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:5180:21)
    at DownloadHttpClient.<anonymous> (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:6986:37)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:6875:71
    at new Promise (<anonymous>)
    at module.exports.855.__awaiter (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:6871:12)
    at makeDownloadRequest (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:6984:47)
    at DownloadHttpClient.<anonymous> (/home/runner/work/_actions/actions/download-artifact/v2.0.9/dist/index.js:7036:38)
    at Generator.next (<anonymous>)
Exponential backoff for retry #1. Waiting for 4728.434905110051 milliseconds before continuing the download
Finished backoff for retry #1, continuing with download

**Comment by konradpabjan** [comment]
v4 has been released today which is a complete rewrite of v1-v3 where this error was occruing: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

With v4 this no longer happens. Recommend switching over today!
