### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by nitish166** [actions/upload-artifact#210]
**Describe the bug**

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**

An error has been caught http-client index 1, retrying the upload
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Exponential backoff for retry #1. Waiting for 5921.453723273494 milliseconds before continuing the upload at offset 0
An error has been caught http-client index 0, retrying the upload
Error: Client has already been disposed.
    at HttpClient.request (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:5694:19)
    at HttpClient.sendStream (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:5655:21)
    at UploadHttpClient.<anonymous> (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:7104:37)
    at Generator.next (<anonymous>)
    at D:\a\_actions\actions\upload-artifact\v2\dist\index.js:6834:71
    at new Promise (<anonymous>)
    at module.exports.608.__awaiter (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:6830:12)
    at uploadChunkRequest (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:7102:46)
    at UploadHttpClient.<anonymous> (D:\a\_actions\actions\upload-artifact\v2\dist\index.js:7139:38)
    at Generator.next (<anonymous>)
Exponential backoff for retry #1. Waiting for 5646.356476531422 milliseconds before continuing the upload at offset 0
Finished backoff for retry #1, continuing with upload
Finished backoff for retry #1, continuing with upload
Total file count: 4995 ---- Processed file #1550 (31.0%)
Total file count: 4995 ---- Processed file #1684 (33.7%)
Total file count: 4995 ---- Processed file #1821 (36.4%)
Total file count: 4995 ---- Processed file #1947 (38.9%)
Total file count: 4995 ---- Processed file #2076 (41.5%)
An error has been caught http-client index 1, retrying the upload
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by nitish166** [comment]
Please help to resolve this issue

**Comment by Vladyslav-Vekslyer** [comment]
Having this same issue as well in a windows environment.

**Comment by konradpabjan** [comment]
v4 has shipped today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

I recommend switching over as these classes of issues should no longer happen with the release
