### ISSUE TITLE
Error: write ECONNRESET

### ISSUE THREAD

**Issue by Vladyslav-Vekslyer** [actions/upload-artifact#226]
**Describe the bug**
Been consistently getting the below error while attempting to upload artifacts. The artifact eventually gets uploaded through enough retries but it stretches a 1 minute upload job to 15 minutes.

```
Exponential backoff for retry #1. Waiting for 5332.956025015754 milliseconds before continuing the upload at offset 0
Finished backoff for retry #1, continuing with upload
Total file count: 84 ---- Processed file #76 (90.4%)
Total file count: 84 ---- Processed file #76 (90.4%)
Total file count: 84 ---- Processed file #76 (90.4%)
Total file count: 84 ---- Processed file #76 (90.4%)
Total file count: 84 ---- Processed file #76 (90.4%)
Total file count: 84 ---- Processed file #76 (90.4%)
An error has been caught http-client index 1, retrying the upload
Error: write ECONNRESET
   at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
 errno: 'ECONNRESET',
 code: 'ECONNRESET',
 syscall: 'write'
}
Exponential backoff for retry #2. Waiting for 13498.66964495308 milliseconds before continuing the upload at offset 0
An error has been caught http-client index 0, retrying the upload
Error: read ECONNRESET
   at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
 errno: 'ECONNRESET',
 code: 'ECONNRESET',
 syscall: 'read'
}
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**How to reproduce**
In a Windows enviroment, attempt to upload an artifact with a high file count(I had 84 files)

**Comment by Vladyslav-Vekslyer** [comment]
Closing since the issue seems to have been resolved already
