### ISSUE TITLE
[bug] Artifact upload fails because permissions insufficient to open target directory

### ISSUE THREAD

**Issue by rcoppy** [actions/upload-artifact#288]
### What happened?

Hello! Quick disclaimer that I'm very new to GitHub Actions--it's quite possible I'm missing something obvious. 

I'm trying to use [game.ci](https://game.ci/docs/github/getting-started) to set up automated cloud builds for a game I'm developing in Unity. 

I'm running upload-artifact v2.3.1, on ubuntu-latest. I don't think(?) I'm using docker, but game.ci might be invoking it under the hood.

Here's my [workflow file](https://github.com/rcoppy/ggj-2022-game/blob/main/.github/workflows/main.yml). 

Here's my [last failed run](https://github.com/rcoppy/ggj-2022-game/runs/4827042418?check_suite_focus=true).

The specific error: 

```
Run actions/upload-artifact@v2.3.1
With the provided path, there will be 15 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "build_WebGL" successfully created. Starting upload of file(s)
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/home/runner/work/ggj-2022-game/ggj-2022-game/build/WebGL/WebGL/Build/WebGL.data.br'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:120:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/runner/work/ggj-2022-game/ggj-2022-game/build/WebGL/WebGL/Build/WebGL.data.br'
}
```

Things to note: 
- The build process for the game is succeeding.
- It looks like something funky might be going on with the way game.ci is configuring the build output path: 
-- `path: '/home/runner/work/ggj-2022-game/ggj-2022-game/build/WebGL/WebGL/Build/WebGL.data.br'`
^ the above has a lot of redundancies.

So far as I can gather from googling around, I've got a permissions problem somewhere. My guess is the permission level set for the build files by game.ci is different from what upload-artifact requires.

Thanks so much for your help! 🙂 

### What did you expect to happen?

upload-artifact should have been able to access the build output from the previous job step.

### How can we reproduce it?

Repo URL: https://github.com/rcoppy/ggj-2022-game

### What version of the action are you using?

v2.3.1

### What are your runner environments?

linux

**Comment by rcoppy** [comment]
Ended up being a problem in game-ci, not upload-artifact; resolved by pinning newest game-ci version (turns out I was a few minor versions behind). Apologies!
