### ISSUE TITLE
[bug] crash on windows

### ISSUE THREAD

**Issue by zkrige** [actions/upload-artifact#536]
### What happened?

crash when running on windows

### What did you expect to happen?

no crash

### How can we reproduce it?

not sure but you can check https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/actions/runs/8149278772/workflow

### Anything else we need to know?

##[debug]Evaluating condition for step: 'Upload the artifacts'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Upload the artifacts
##[debug]Loading inputs
##[debug]Loading env
Run actions/upload-artifact@v4
  with:
    name: win
    path: c:/a/**/build/out/*.zip
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
##[debug]followSymbolicLinks 'true'
##[debug]implicitDescendants 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]followSymbolicLinks 'true'
##[debug]implicitDescendants 'true'
##[debug]matchDirectories 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]Search path 'c:\a'
Error: Cannot read properties of undefined (reading '0')
node:internal/fs/promises:894
  const result = await binding.stat(pathModule.toNamespacedPath(path),
                               ^

Error: ENOENT: no such file or directory, stat
    at Object.stat (node:internal/fs/promises:894:32)
    at DefaultGlobber.<anonymous> (D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:9135:47)
    at Generator.next (<anonymous>)
    at D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:8965:71
    at new Promise (<anonymous>)
    at __webpack_modules__.28298.__awaiter (D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:8961:12)
    at DefaultGlobber.stat (D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:9127:16)
    at DefaultGlobber.globGenerator_1 (D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:9072:60)
    at globGenerator_1.next (<anonymous>)
    at resume (D:\a\_actions\actions\upload-artifact\v4\dist\upload\index.js:8981:44) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat'
}

Node.js v20.8.1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Upload the artifacts

### What version of the action are you using?

uses: actions/upload-artifact@v4

### What are your runner environments?

window

**Comment by zkrige** [comment]
same issue on 4.3.1 on windows

Run actions/upload-artifact@v4.3.1
  with:
    name: win
    path: c:/a/**/build/out/*.zip
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
Error: Cannot read properties of undefined (reading '0')
node:internal/fs/promises:894
  const result = await binding.stat(pathModule.toNamespacedPath(path),
                               ^

Error: ENOENT: no such file or directory, stat
    at Object.stat (node:internal/fs/promises:894:32)
    at DefaultGlobber.<anonymous> (D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:9135:47)
    at Generator.next (<anonymous>)
    at D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:8965:71
    at new Promise (<anonymous>)
    at __webpack_modules__.28298.__awaiter (D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:8961:12)
    at DefaultGlobber.stat (D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:9127:16)
    at DefaultGlobber.globGenerator_1 (D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:9072:60)
    at globGenerator_1.next (<anonymous>)
    at resume (D:\a\_actions\actions\upload-artifact\v4.3.1\dist\upload\index.js:8981:44) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat'
}

Node.js v20.8.1

**Comment by marauder2k7** [comment]
same issue
